# Install settings
install_source: https://github.com/bcpierce00/unison/releases/download/v2.52.1/unison-v2.52.1+ocaml-4.14.0+x86_64.linux.tar.gz
install_destiny: /opt/unison
# Unison Manager settings
log_file: /opt/unison/unisonManager.log
# Unison settings
unison_profile_directory: /root/.unison/profiles
# Crontab settings
unison_crontab_default_schedule: '* * * * *'
unison_contrab_path: /etc/cron.d
